#! ruby
require 'test/unit'
require 'user_space'
require './test/lib/appdir.rb' # provides DIRN

GEMDIR = __dir__
class TestAppDir < Test::Unit::TestCase
  def test_appdir
    assert_equal GEMDIR, DIR1
    assert_equal GEMDIR, DIR2
    assert_equal GEMDIR, DIR3
    assert_equal GEMDIR, DIR4
    assert_equal GEMDIR, DIR5
    assert_equal GEMDIR, DIR6
  end
end
