#! ruby
require 'test/unit'
require 'tmpdir'
require 'json'

TMPDIR      = Dir.mktmpdir
Dir.mkdir File.join TMPDIR, '.cache'
Dir.mkdir File.join TMPDIR, '.config'
Dir.mkdir File.join TMPDIR, '.local'
Dir.mkdir File.join TMPDIR, '.local', 'share'
APPNAME     = 'ima2awesome'

ENV['HOME'] = TMPDIR
$0          = APPNAME

# Needed to setup the enviroment first, now...
require 'user_space'

class TestUserSpace < Test::Unit::TestCase

  def test_user_space_version
    assert_equal('5.0.210123', UserSpace::VERSION)
  end

  def test_user_space_new
    userspace = nil
    assert_nothing_raised(Exception){userspace = UserSpace.new(parser:JSON)}

    assert_equal(APPNAME, userspace.appname)

    dirname = File.dirname File.dirname File.expand_path __FILE__
    assert_equal(dirname, userspace.appdir)

    xdgbases = userspace.xdgbases
    assert(xdgbases.include?('cache'))
    assert(xdgbases.include?('config'))
    assert(xdgbases.include?('data'))

    count = 0
    userspace.xdg_pairs do |basedir, userdir|
      count += 1
      assert(File.directory?(userdir))
      refute_nil(userdir=~/\/ima2awesome$/)
      refute_nil(basedir=~/user_space\/((data)|(config)|(cache))$/)
    end
    assert_equal(3, count)

    cachedir, configdir, datadir = userspace.cachedir, userspace.configdir, userspace.datadir
    assert File.exist? cachedir
    assert File.exist? configdir
    assert File.exist? datadir

    config_file_name = userspace.config_file_name
    refute File.exist? config_file_name
    config1 = {'a'=>"A", 'b'=>"B"}
    userspace.config = config1
    assert File.exist? config_file_name
    config2 = JSON.parse File.read config_file_name
    assert_equal config1, config2

    stat = File.stat config_file_name
    assert_equal stat.mode.to_s(8), '100600'

    [cachedir, configdir, datadir].each do |dn|
      stat = File.stat(dn)
      assert_equal stat.mode.to_s(8), '40700'
    end

    # testing configures
    config_file_name = userspace.config_file_name
    File.unlink config_file_name if File.exist? config_file_name
    config1 = {'a'=>'A', 'b'=>'B'}
    refute File.exist? config_file_name
    userspace.configures(config1)
    # Here, it copies to file.
    assert File.exist? config_file_name
    # And config1 remains unchanged.
    assert_equal(config1['a'], 'A')
    assert_equal(config1['b'], 'B')
    assert_equal(config1['c'], nil)
    config2 = {'a'=>'AAA', 'c'=>'CCC'}
    # Here, config2 is overwritten with config1 from file.
    userspace.configures(config2)
    assert_equal(config2['a'], 'A')   # overwritten
    assert_equal(config2['b'], 'B')   # padded up
    assert_equal(config2['c'], 'CCC') # Original value
  end
end
